# Site settings
title: TMull | Tyron Mullins
description: 'General blog of my work and other stuff I get up to. Formaly structural enggineer at Price & Myers'
url: 'http://tmull.com'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Tyron Mullins'
  email: tyronmullins@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  MullT3
  linkedin_username:  tyron-mullins-9bb084ab

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
